spring:
    # 数据源
    datasource:
        url: jdbc:mysql://localhost:3306/news_release_system?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    # 文件
    servlet:
        multipart:
            enabled: true
            #最大支持文件大小
            max-file-size: 100MB
            #最大支持请求大小
            max-request-size: 100MB

server:
    port: 8000


